# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macOS-latest' ]
        r: [ 'devel', 'release', 'oldrel-1', '4.3.3', '4.2.3', '4.1.3', '4.0.5', '3.6.1' ]
        java: [ '17', '19', '21' ]
        include:
          - http-user-agent: 'release'
            r: 'devel'

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: ${{ matrix.java }}

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          http-user-agent: ${{ matrix.http-user-agent }}
          use-public-rspm: true

      - name: Set up for RProtoBuf on Windows
        if: runner.os == 'Windows'
        run: choco install protoc

      - name: Set up for RProtoBuf on macos
        if: runner.os == 'macOS'
        run: brew install protobuf

      - name: Set up for RProtoBuf on ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install protobuf-compiler libprotobuf-dev libprotoc-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          upload-results: true
          # build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
          error-on: '"note"'
